var tree = [["Icecave",,"",
                [["Dialekt","Icecave\/Dialekt.html","",
                [["AST","Icecave\/Dialekt\/AST.html","",
                [["AbstractPolyadicOperator","Icecave\/Dialekt\/AST\/AbstractPolyadicOperator.html","",
                [        ]],["EmptyExpression","Icecave\/Dialekt\/AST\/EmptyExpression.html","",
                [        ]],["ExpressionInterface","Icecave\/Dialekt\/AST\/ExpressionInterface.html","",
                [        ]],["LogicalAnd","Icecave\/Dialekt\/AST\/LogicalAnd.html"," < AbstractPolyadicOperator",
                [        ]],["LogicalNot","Icecave\/Dialekt\/AST\/LogicalNot.html","",
                [        ]],["LogicalOr","Icecave\/Dialekt\/AST\/LogicalOr.html"," < AbstractPolyadicOperator",
                [        ]],["NodeInterface","Icecave\/Dialekt\/AST\/NodeInterface.html","",
                [        ]],["Pattern","Icecave\/Dialekt\/AST\/Pattern.html","",
                [        ]],["PatternChildInterface","Icecave\/Dialekt\/AST\/PatternChildInterface.html","",
                [        ]],["PatternLiteral","Icecave\/Dialekt\/AST\/PatternLiteral.html","",
                [        ]],["PatternWildcard","Icecave\/Dialekt\/AST\/PatternWildcard.html","",
                [        ]],["Tag","Icecave\/Dialekt\/AST\/Tag.html","",
                [        ]],["VisitorInterface","Icecave\/Dialekt\/AST\/VisitorInterface.html","",
                [        ]]        ]],["Evaluator","Icecave\/Dialekt\/Evaluator.html","",
                [["Evaluator","Icecave\/Dialekt\/Evaluator\/Evaluator.html","",
                [        ]]        ]],["Parser","Icecave\/Dialekt\/Parser.html","",
                [["Exception","Icecave\/Dialekt\/Parser\/Exception.html","",
                [["ParseException","Icecave\/Dialekt\/Parser\/Exception\/ParseException.html"," < Exception",
                [        ]]        ]],["Lexer","Icecave\/Dialekt\/Parser\/Lexer.html","",
                [        ]],["LexerInterface","Icecave\/Dialekt\/Parser\/LexerInterface.html","",
                [        ]],["Parser","Icecave\/Dialekt\/Parser\/Parser.html","",
                [        ]],["ParserInterface","Icecave\/Dialekt\/Parser\/ParserInterface.html","",
                [        ]],["Token","Icecave\/Dialekt\/Parser\/Token.html","",
                [        ]]        ]],["Renderer","Icecave\/Dialekt\/Renderer.html","",
                [["Exception","Icecave\/Dialekt\/Renderer\/Exception.html","",
                [["RenderException","Icecave\/Dialekt\/Renderer\/Exception\/RenderException.html"," < Exception",
                [        ]]        ]],["ExpressionRenderer","Icecave\/Dialekt\/Renderer\/ExpressionRenderer.html","",
                [        ]],["RendererInterface","Icecave\/Dialekt\/Renderer\/RendererInterface.html","",
                [        ]],["TreeRenderer","Icecave\/Dialekt\/Renderer\/TreeRenderer.html","",
                [        ]]        ]],["PackageInfo","Icecave\/Dialekt\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

