var tree = [["Icecave",,"",
                [["Dialekt","Icecave\/Dialekt.html","",
                [["AST","Icecave\/Dialekt\/AST.html","",
                [["AbstractExpression","Icecave\/Dialekt\/AST\/AbstractExpression.html","",
                [        ]],["AbstractPolyadicExpression","Icecave\/Dialekt\/AST\/AbstractPolyadicExpression.html"," < AbstractExpression",
                [        ]],["EmptyExpression","Icecave\/Dialekt\/AST\/EmptyExpression.html"," < AbstractExpression",
                [        ]],["ExpressionInterface","Icecave\/Dialekt\/AST\/ExpressionInterface.html","",
                [        ]],["LogicalAnd","Icecave\/Dialekt\/AST\/LogicalAnd.html"," < AbstractPolyadicExpression",
                [        ]],["LogicalNot","Icecave\/Dialekt\/AST\/LogicalNot.html"," < AbstractExpression",
                [        ]],["LogicalOr","Icecave\/Dialekt\/AST\/LogicalOr.html"," < AbstractPolyadicExpression",
                [        ]],["NodeInterface","Icecave\/Dialekt\/AST\/NodeInterface.html","",
                [        ]],["Pattern","Icecave\/Dialekt\/AST\/Pattern.html"," < AbstractExpression",
                [        ]],["PatternChildInterface","Icecave\/Dialekt\/AST\/PatternChildInterface.html","",
                [        ]],["PatternLiteral","Icecave\/Dialekt\/AST\/PatternLiteral.html","",
                [        ]],["PatternWildcard","Icecave\/Dialekt\/AST\/PatternWildcard.html","",
                [        ]],["Tag","Icecave\/Dialekt\/AST\/Tag.html"," < AbstractExpression",
                [        ]],["VisitorInterface","Icecave\/Dialekt\/AST\/VisitorInterface.html","",
                [        ]]        ]],["Evaluator","Icecave\/Dialekt\/Evaluator.html","",
                [["EvaluationResult","Icecave\/Dialekt\/Evaluator\/EvaluationResult.html","",
                [        ]],["Evaluator","Icecave\/Dialekt\/Evaluator\/Evaluator.html","",
                [        ]],["EvaluatorInterface","Icecave\/Dialekt\/Evaluator\/EvaluatorInterface.html","",
                [        ]],["ExpressionResult","Icecave\/Dialekt\/Evaluator\/ExpressionResult.html","",
                [        ]]        ]],["Parser","Icecave\/Dialekt\/Parser.html","",
                [["Exception","Icecave\/Dialekt\/Parser\/Exception.html","",
                [["ParseException","Icecave\/Dialekt\/Parser\/Exception\/ParseException.html"," < Exception",
                [        ]]        ]],["AbstractParser","Icecave\/Dialekt\/Parser\/AbstractParser.html","",
                [        ]],["ExpressionParser","Icecave\/Dialekt\/Parser\/ExpressionParser.html"," < AbstractParser",
                [        ]],["Lexer","Icecave\/Dialekt\/Parser\/Lexer.html","",
                [        ]],["LexerInterface","Icecave\/Dialekt\/Parser\/LexerInterface.html","",
                [        ]],["ListParser","Icecave\/Dialekt\/Parser\/ListParser.html"," < AbstractParser",
                [        ]],["ParserInterface","Icecave\/Dialekt\/Parser\/ParserInterface.html","",
                [        ]],["Token","Icecave\/Dialekt\/Parser\/Token.html","",
                [        ]]        ]],["Renderer","Icecave\/Dialekt\/Renderer.html","",
                [["Exception","Icecave\/Dialekt\/Renderer\/Exception.html","",
                [["RenderException","Icecave\/Dialekt\/Renderer\/Exception\/RenderException.html"," < Exception",
                [        ]]        ]],["ExpressionRenderer","Icecave\/Dialekt\/Renderer\/ExpressionRenderer.html","",
                [        ]],["RendererInterface","Icecave\/Dialekt\/Renderer\/RendererInterface.html","",
                [        ]],["TreeRenderer","Icecave\/Dialekt\/Renderer\/TreeRenderer.html","",
                [        ]]        ]],["PackageInfo","Icecave\/Dialekt\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

